# Generated by Django 4.1.5 on 2023-01-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DlmCust',
            fields=[
                ('iddlm_cust', models.AutoField(db_column='idDLM_CUST', primary_key=True, serialize=False)),
                ('dlm_cust_tntid', models.CharField(db_column='DLM_CUST_TNTID', max_length=50)),
                ('dlm_cust_nam', models.CharField(db_column='DLM_CUST_NAM', max_length=50)),
                ('dlm_cust_mobnum', models.IntegerField(db_column='DLM_CUST_MOBNUM', unique=True)),
                ('dlm_cust_email', models.EmailField(db_column='DLM_CUST_EMAIL', max_length=50, unique=True)),
                ('dlm_cust_diml', models.CharField(db_column='DLM_CUST_DIML', max_length=50)),
                ('dlm_cust_cdate', models.DateTimeField(blank=True, db_column='DLM_CUST_CDATE', null=True)),
            ],
            options={
                'db_table': 'dlm_cust',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DlmCustuser',
            fields=[
                ('iddlm_custuser', models.AutoField(db_column='idDLM_CUSTUSER', primary_key=True, serialize=False)),
                ('dlm_custuser_grpid', models.CharField(db_column='DLM_CUSTUSER_GRPID', max_length=250)),
                ('dlm_custuser_custid', models.CharField(db_column='DLM_CUSTUSER_CUSTID', max_length=250)),
                ('dlm_custuser_code', models.CharField(db_column='DLM_CUSTUSER_CODE', max_length=250)),
                ('dlm_custuser_pwd', models.CharField(db_column='DLM_CUSTUSER_PWD', max_length=50)),
                ('dlm_custuser_type', models.CharField(db_column='DLM_CUSTUSER_TYPE', max_length=45)),
                ('dlm_custuser_date', models.DateTimeField(blank=True, db_column='DLM_CUSTUSER_DATE', null=True)),
                ('dlm_custuser_verify', models.IntegerField(db_column='DLM_CUSTUSER_VERIFY')),
            ],
            options={
                'db_table': 'dlm_custuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DlmGroup',
            fields=[
                ('iddlm_group', models.AutoField(db_column='idDLM_GROUP', primary_key=True, serialize=False)),
                ('dlm_group_custid', models.CharField(db_column='DLM_GROUP_CUSTID', max_length=250)),
                ('dlm_group_code', models.CharField(db_column='DLM_GROUP_CODE', max_length=250)),
                ('dlm_group_des', models.CharField(db_column='DLM_GROUP_DES', max_length=100)),
                ('dlm_group_activity', models.TextField(blank=True, db_column='DLM_GROUP_ACTIVITY', null=True)),
                ('dlm_group_cdate', models.DateTimeField(blank=True, db_column='DLM_GROUP_CDATE', null=True)),
            ],
            options={
                'db_table': 'dlm_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DlmTenant',
            fields=[
                ('iddlm_tenant', models.AutoField(db_column='idDLM_TENANT', primary_key=True, serialize=False)),
                ('dlm_tenant_nam', models.CharField(db_column='DLM_TENANT_NAM', max_length=50)),
                ('dlm_tenant_secky', models.CharField(db_column='DLM_TENANT_SECKY', max_length=5)),
                ('dlm_tenant_sts', models.CharField(db_column='DLM_TENANT_STS', max_length=250)),
                ('dlm_tenant_cdate', models.DateTimeField(blank=True, db_column='DLM_TENANT_CDATE', null=True)),
                ('dlm_tenant_cat', models.CharField(db_column='DLM_TENANT_CAT', max_length=45)),
            ],
            options={
                'db_table': 'dlm_tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dlt_passreset',
            fields=[
                ('iddlt_passreset', models.AutoField(db_column='idDLT_PASSRESET', primary_key=True, serialize=False)),
                ('dlt_passreset_usrid', models.IntegerField(db_column='DLT_PASSRESET_USRID', default='')),
                ('dlt_passreset_otpcode', models.CharField(db_column='DLT_PASSRESET_OTPCODE', max_length=45)),
                ('dlt_passreset_expdate', models.DateTimeField()),
                ('dlt_passreset_cdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'dlt_passreset',
                'managed': False,
            },
        ),
    ]
