# Generated by Django 4.1.5 on 2023-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daefodilapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlm_docmap',
            fields=[
                ('iddlm_docmap', models.AutoField(db_column='idDLM_DOCMAP', primary_key=True, serialize=False)),
                ('dlm_docmap_clientid', models.IntegerField(db_column='DLM_DOCMAP_CLIENTID')),
                ('dlm_docmap_dtype', models.CharField(db_column='DLM_DOCMAP_DTYPE', max_length=100)),
                ('dlm_docmap_element', models.CharField(db_column='DLM_DOCMAP_ELEMENT', max_length=600)),
                ('dlm_docmap_cname', models.CharField(db_column='DLM_DOCMAP_CNAME', max_length=100)),
                ('dlm_docmap_uid', models.IntegerField(db_column='DLM_DOCMAP_UID')),
            ],
            options={
                'db_table': 'dlm_docmap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dlm_doctype',
            fields=[
                ('iddlm_doctype', models.AutoField(db_column='idDLM_DOCTYPE', primary_key=True, serialize=False)),
                ('dlm_doctype_nam', models.CharField(blank=True, db_column='DLM_DOCTYPE_NAM', max_length=5, null=True)),
                ('dlm_doctype_catgrp', models.CharField(blank=True, db_column='DLM_DOCTYPE_CATGRP', max_length=5, null=True)),
                ('dlm_doctype_cdate', models.DateTimeField(blank=True, db_column='DLM_DOCTYPE_CDATE', null=True)),
                ('dlm_doctype_cby', models.CharField(blank=True, db_column='DLM_DOCTYPE_CBY', max_length=45, null=True)),
            ],
            options={
                'db_table': 'dlm_doctype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dlm_plan',
            fields=[
                ('iddlm_plan', models.AutoField(db_column='idDLM_PLAN', primary_key=True, serialize=False)),
                ('dlm_plan_catgrp', models.CharField(db_column='DLM_PLAN_CATGRP', max_length=50)),
                ('dlm_plan_nam', models.CharField(db_column='DLM_PLAN_NAM', max_length=50)),
                ('dlm_plan_trncnt', models.CharField(db_column='DLM_PLAN_TRNCNT', max_length=50)),
                ('dlm_plan_usrcnt', models.IntegerField(db_column='DLM_PLAN_USRCNT')),
                ('dlm_plan_filesize', models.CharField(db_column='DLM_PLAN_FILESIZE', max_length=50)),
                ('dlm_plan_catsize', models.CharField(db_column='DLM_PLAN_CATSIZE', max_length=50)),
                ('dlm_plan_cdate', models.DateTimeField(db_column='DLM_PLAN_CDATE')),
                ('dlm_plan_cby', models.CharField(db_column='DLM_PLAN_CBY', default='superadmin', max_length=50)),
                ('dlm_plan_status', models.CharField(db_column='DLM_PLAN_STATUS', default='active', max_length=50)),
                ('dlm_plan_usrtype', models.CharField(blank=True, db_column='DLM_PLAN_USRTYPE', max_length=45, null=True)),
                ('dlm_plan_featureid', models.CharField(db_column='DLM_PLAN_FEATURE', max_length=50)),
            ],
            options={
                'db_table': 'dlm_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dlm_price',
            fields=[
                ('iddlm_price', models.AutoField(db_column='idDLM_PRICE', primary_key=True, serialize=False)),
                ('dlm_price_planid', models.IntegerField(db_column='DLM_PRICE_PLANID')),
                ('dlm_price_valtype', models.CharField(db_column='DLM_PRICE_VALTYPE', max_length=50)),
                ('dlm_price_amt', models.IntegerField(db_column='DLM_PRICE_AMT')),
                ('dlm_price_cdate', models.DateTimeField(db_column='DLM_PRICE_CDATE')),
                ('dlm_price_cby', models.CharField(db_column='DLM_PRICE_CBY', default='superadmin', max_length=50)),
            ],
            options={
                'db_table': 'dlm_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DlmFeature',
            fields=[
                ('iddlm_feature', models.AutoField(db_column='idDLM_FEATURE', primary_key=True, serialize=False)),
                ('dlm_feature_name', models.CharField(blank=True, db_column='DLM_FEATURE_NAME', max_length=45, null=True)),
                ('dlm_feature_desc', models.CharField(db_column='DLM_FEATURE_DESC', max_length=45)),
                ('dlm_feature_cdate', models.DateTimeField(blank=True, db_column='DLM_FEATURE_CDATE', null=True)),
                ('dlm_feature_cby', models.CharField(db_column='DLM_FEATURE_CBY', max_length=45)),
            ],
            options={
                'db_table': 'dlm_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dlt_melements',
            fields=[
                ('iddlt_melements', models.AutoField(db_column='idDLT_MELEMENTS', primary_key=True, serialize=False)),
                ('dlt_melements_tid', models.IntegerField(db_column='DLT_MELEMENTS_TID')),
                ('dlt_melements_cid', models.IntegerField(db_column='DLT_MELEMENTS_CID')),
                ('dlt_melements_dtype', models.CharField(db_column='DLT_MELEMENTS_DTYPE', max_length=100)),
                ('dlt_melements_1', models.CharField(db_column='DLT_MELEMENTS_1', max_length=200)),
                ('dlt_melements_2', models.CharField(db_column='DLT_MELEMENTS_2', max_length=200)),
                ('dlt_melements_3', models.CharField(db_column='DLT_MELEMENTS_3', max_length=200)),
                ('dlt_melements_4', models.CharField(db_column='DLT_MELEMENTS_4', max_length=200)),
                ('dlt_melements_5', models.CharField(db_column='DLT_MELEMENTS_5', max_length=200)),
                ('dlt_melements_6', models.CharField(db_column='DLT_MELEMENTS_6', max_length=200)),
                ('dlt_melements_7', models.CharField(db_column='DLT_MELEMENTS_7', max_length=200)),
                ('dlt_melements_8', models.CharField(db_column='DLT_MELEMENTS_8', max_length=200)),
                ('dlt_melements_9', models.CharField(db_column='DLT_MELEMENTS_9', max_length=200)),
                ('dlt_melements_10', models.CharField(db_column='DLT_MELEMENTS_10', max_length=200)),
                ('dlt_melements_11', models.CharField(db_column='DLT_MELEMENTS_11', max_length=200)),
                ('dlt_melements_12', models.CharField(db_column='DLT_MELEMENTS_12', max_length=200)),
                ('dlt_melements_13', models.CharField(db_column='DLT_MELEMENTS_13', max_length=200)),
                ('dlt_melements_14', models.CharField(db_column='DLT_MELEMENTS_14', max_length=200)),
                ('dlt_melements_15', models.CharField(db_column='DLT_MELEMENTS_15', max_length=200)),
                ('dlt_melements_uid', models.CharField(db_column='DLT_MELEMENTS_UID', max_length=200)),
                ('dlt_melements_cdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'dlt_melements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DltDocproc',
            fields=[
                ('iddlt_docproc', models.AutoField(db_column='idDLT_DOCPROC', primary_key=True, serialize=False)),
                ('dlt_docproc_userid', models.IntegerField(db_column='DLT_DOCPROC_USERID')),
                ('dlt_docproc_filesize', models.CharField(blank=True, db_column='DLT_DOCPROC_FILESIZE', max_length=5, null=True)),
                ('dlt_docproc_filetype', models.CharField(blank=True, db_column='DLT_DOCPROC_FILETYPE', max_length=50, null=True)),
                ('dlt_docproc_filename', models.CharField(blank=True, db_column='DLT_DOCPROC_FILENAME', max_length=100, null=True)),
                ('dlt_docproc_cdate', models.DateTimeField(blank=True, db_column='DLT_DOCPROC_CDATE', null=True)),
                ('dlt_docproc_sts', models.CharField(blank=True, db_column='DLT_DOCPROC_STS', max_length=100, null=True)),
                ('dlt_docproc_accrcy', models.CharField(blank=True, db_column='DLT_DOCPROC_ACCRCY', max_length=100, null=True)),
                ('dlt_docproc_dataid', models.IntegerField(blank=True, db_column='DLT_DOCPROC_DATAID', null=True)),
                ('dlt_docproc_dwldsts', models.CharField(blank=True, db_column='DLT_DOCPROC_DWLDSTS', max_length=45, null=True)),
            ],
            options={
                'db_table': 'dlt_docproc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='View2',
            fields=[
                ('dlm_pricingpage_id', models.AutoField(db_column='idDLM_PRICE', primary_key=True, serialize=False)),
                ('iddlm_plan', models.IntegerField(db_column='idDLM_PLAN')),
                ('dlm_plan_nam', models.CharField(blank=True, db_column='DLM_PLAN_NAM', max_length=45, null=True)),
                ('dlm_price_amt', models.CharField(db_column='DLM_PRICE_AMT', max_length=45)),
                ('dlm_price_valtype', models.CharField(db_column='DLM_PRICE_VALTYPE', max_length=5)),
                ('dlm_plan_usrtype', models.CharField(db_column='DLM_PLAN_USRTYPE', max_length=5)),
                ('dlm_plan_feature', models.CharField(db_column='DLM_PLAN_FEATURE', max_length=5)),
            ],
            options={
                'db_table': 'view2',
                'managed': False,
            },
        ),
    ]
